package:
  name: toolchain
  version: 2.5.0

build:
  number: 0
  skip: True  # [not win]

outputs:
  - name: m2w64-toolchain_{{ target_platform }}
    requirements:
      - m2w64-toolchain
    run_exports:
      strong:
        - m2w64-gcc-libs
        - m2w64-gcc-libs-core
    test:
      commands:
        - echo hello

about:
  home: https://github.com/conda-forge/toolchain-feedstock
  license: BSD-3-Clause
  summary: A meta-package to enable the right toolchain.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - patricksnape
    - pelson
    - scopatz
