package:
  name: toolchain
  version: 2.1.0

build:
  number: 0

test:
  commands:
    # Verify the scripts are in-place.
    {% for state in ["activate", "deactivate"] %}
    - test -f "${PREFIX}/etc/conda/{{ state }}.d/toolchain_{{ state }}.sh"                        # [unix]
    - if not exist %PREFIX%\\etc\\conda\\{{ state }}.d\\toolchain_{{ state }}.bat exit 1  # [win]
    {% endfor %}

about:
  home: https://github.com/conda-forge/toolchain-feedstock
  license: BSD 3-Clause
  summary: A meta-package to enable the right toolchain.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - patricksnape
    - pelson
    - scopatz
