travis:
  secure:
    BINSTAR_TOKEN: dP5ewGUcpYPx57Y++IXw8UfbHYKgiL67bgJAzHvFTbqb/GTdhR3T7r310E/HV5pwiRYSSgoD58HJd6YuM4XslWH69GdvVmytkTXUYfM+QS1X7f8/vRx7oOjibPfKCRmjwmcIBXQ0ZH7Bm//A9dTvurP6ksm/5nqxj+CKQS/5jH3x0PRjcyi61g0Bs89tAy1SPt0Vpf0FAeiDswyQ0KOkM95aWQ8Kh3jvBA6llygYVm8Fnxp5tadIeJbjppUtAMokU+bSynI8OanuIzfmMl6OUeD1qcQ+jLvoDSBENEdE5R8uNfiekSWyjzpHPuncFUMjNy4fm+1AW0R0kzmR+VU946Eab2IxTR3y3SsnMM7D12y054WPE93lkXV1AByUC9D9HRnNOT+NEnenKrs+aegF8mb2KRibE4TC0n9hxLusu8Jnab2zpU4uU21QV73ScjbQi50cY/YEb1jBOr8DjewqXpbjDisVf6ceXWLecWXPkMbfXld6ShgS3PhEr+ucBRD0mF1XKdOUAEV5ApbwuIRZ7coMiPqNiE1Xi6Qx32HI78WQdSWldhM6BUrNzvgFY4NIZfeIrh404woUytzNWB7JFXHrPcpPBcNboHiyAFiTpezk0DjJASdyPlc3lXMT6quWVVnbXQOFmtsqO13ZXfjzca7JEBmlQQuOATwioXxntfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
